name: data_TRKJ
description: Data Mahasiswa Trkj.
publish_to: 'none'

version: 1.1.0

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cupertino_icons: ^1.0.2
  flutter_typeahead: ^4.8.0
  flutter_launcher_icons: ^0.13.1
  android_intent: ^2.0.0
  url_launcher: ^6.1.14
  url_launcher_android: ^6.1.0
  url_launcher_platform_interface: ^2.1.5

flutter_icons:
  android: true
  ios: true
  image_path: "icons/png/logo-color.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
